// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  angular.module('gifpumper', ['ngCookies', 'ngResource', 'ngSanitize', 'ngRoute']).config(function($routeProvider, $locationProvider, $httpProvider) {
    $routeProvider.when("/", {
      templateUrl: "partials/index",
      controller: 'MainCtrl'
    }).when("/profile/:userName", {
      templateUrl: "partials/user",
      controller: 'userCtrl'
    }).when("/:pageName", {
      templateUrl: "partials/page",
      controller: 'MainCtrl'
    }).otherwise({
      redirectTo: '/'
    });
    return $locationProvider.html5Mode(true);
  });

}).call(this);
